//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyndicationService.RssDataServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RssDataServiceReference.IRssDataService")]
    public interface IRssDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRssDataService/GetListRssArticle", ReplyAction="http://tempuri.org/IRssDataService/GetListRssArticleResponse")]
        IziWatch.DBO.RssArticle[] GetListRssArticle();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRssDataService/GetListRssArticle", ReplyAction="http://tempuri.org/IRssDataService/GetListRssArticleResponse")]
        System.Threading.Tasks.Task<IziWatch.DBO.RssArticle[]> GetListRssArticleAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRssDataServiceChannel : SyndicationService.RssDataServiceReference.IRssDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RssDataServiceClient : System.ServiceModel.ClientBase<SyndicationService.RssDataServiceReference.IRssDataService>, SyndicationService.RssDataServiceReference.IRssDataService {
        
        public RssDataServiceClient() {
        }
        
        public RssDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RssDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RssDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RssDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public IziWatch.DBO.RssArticle[] GetListRssArticle() {
            return base.Channel.GetListRssArticle();
        }
        
        public System.Threading.Tasks.Task<IziWatch.DBO.RssArticle[]> GetListRssArticleAsync() {
            return base.Channel.GetListRssArticleAsync();
        }
    }
}
